CREATE DATABASE DATABASE_LINKS;

USE DATABASE_LINKS;

CREATE TABLE USERS(
    ID INT(11) NOT NULL,
    USERNAME VARCHAR(16) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    FULLNAME VARCHAR(100) NOT NULL
);

ALTER TABLE
    USERS
ADD
    PRIMARY KEY (ID);

ALTER TABLE
    USERS
MODIFY
    ID INT(11) NOT NULL AUTO_INCREMENT,
    AUTO_INCREMENT = 2;

DESCRIBE USERS;

CREATE TABLE LINKS(
    ID INT(11) NOT NULL,
    TITLE VARCHAR(150) NOT NULL,
    URL VARCHAR(255) NOT NULL,
    DESCRITPION TEXT,
    USER_ID INT(11),
    CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

ALTER TABLE
    LINKS
ADD
    PRIMARY KEY (ID);

ALTER TABLE
    LINKS
MODIFY
    ID INT(11) NOT NULL AUTO_INCREMENT,
    AUTO_INCREMENT = 2;

DESCRIBE LINKS;